### ISSUE TITLE
Empty jar from mvn install

### ISSUE THREAD

**Issue by steely-glint** [CaliDog/certstream-java#1]
Looks like the pom.xml does not find any sources. 
I tried moving src/* to src/java/main and got a better build.

**Comment by Fitblip** [comment]
![](https://media0.giphy.com/media/GDnomdqpSHlIs/giphy.gif)

Hey @steely-glint,

Sorry about that! This is a new project so there will inevitably be a bit of breakage, and it sounds like you found some! 

@joshbooks will take a look when he gets a chance and this should be solved within a day (2-3 max depending on his schedule).

Thanks for the bug! :D

**Comment by Fitblip** [comment]
This should be fixed with https://github.com/CaliDog/certstream-java/commit/f461f006bbfdd724cf541f33d91b6d67bffa179d. Closing. 

Thanks again for the report + fix @steely-glint - we greatly appreciate it! Have a great rest of your week :).

**Comment by NthPortal** [comment]
Could you publish the fixed version to JitPack please?

**Comment by joshbooks** [comment]
Absolutely, I’ll get it fixed within a day or two

**Comment by joshbooks** [comment]
@NthPortal if you try again with the new dependency in the new README everything should work :)

**Comment by NthPortal** [comment]
It works! Thanks!
