### ISSUE TITLE
Log spam: certstream.BoringParts

### ISSUE THREAD

**Issue by Tim269** [CaliDog/certstream-java#3]
Thanks for this repo! Using it now for a few hours. However my log gets spammed with this message:
```
WARN certstream.BoringParts: OnClose was called wih i = 1006, s = , b = b
```
Is there a way I can suppress this?

**Comment by joshbooks** [comment]
Just changed log level to debug, better now?

**Comment by Tim269** [comment]
Thanks. Could you might remove the System.out.println at all? https://github.com/CaliDog/certstream-java/blob/master/src/io/calidog/certstream/BoringParts.java#L50

**Comment by joshbooks** [comment]
Done 👍

**Comment by Tim269** [comment]
Thank you for your fast help! I'm looking forward for a new small release.
