### ISSUE TITLE
Stream ends after 1 min

### ISSUE THREAD

**Issue by Tim269** [CaliDog/certstream-java#4]
Hey there! I really love this project and the possibilities it does offer. Sadly recently it did somehow break. When I use the following as a test code:
```java
public static void main(String[] args){
        CertStream.onMessageString(msg -> {
        	JSONArray jsonArray =  new JSONObject(msg).getJSONObject("data").getJSONObject("leaf_cert").getJSONArray("all_domains");
        	for(Object domain : jsonArray) {
        		System.out.println(domain.toString());        			
        	}
        });    	
}
```
The stream / program does just stop after about 1 minute or 7k - 8k domains.

Is there something I do wrong? Or did something else change? Thank you!

**Comment by Tim269** [comment]
Ah Sorry. I found the answer on the other projects. As temp fix I'll run a cron every minute.

**Comment by joshbooks** [comment]
@Schneidertm I didn’t know about this limit (I assume @Fitblip put something in place?) could you link me to where you found this answer?

**Comment by Tim269** [comment]
Correct. Oh yeah sorry I forgot to link them, here they are:

https://github.com/CaliDog/certstream-python/issues/27
https://github.com/CaliDog/certstream-go/issues/8

and
https://github.com/ninenines/cowboy/issues/1259

**Comment by Fitblip** [comment]
Just to close the loop here, we need to send an occasional ping from the clients to ensure the server doesn't assume they're dead. I originally just had the timeout set to something really high but that (understandably) causes issues on the public server.
