### ISSUE TITLE
IllegalStateException if entry contains "extra" field

### ISSUE THREAD

**Issue by nitram22** [CaliDog/certstream-java#7]
Hi guys,

while running the onMessage method I noticed that from time to time incoming messages throw an error like` "java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 7984 path $.data.leaf_cert.extensions."` . 

I did some debugging and found out that the error occurs when a CT-Log entry has the field under `"leaf_cert"` --> `"extensions"` --> `"extra"` that begins with an array. I've added a picture of an entry that produced an error: 

![issue](https://user-images.githubusercontent.com/62987795/78670164-a5069900-78dd-11ea-8d7e-bbd443011c79.JPG)

CT-Log entries that don't contain this "extra" field get parsed normally.  Here's the Stack-Trace:

[stacktrace.txt](https://github.com/CaliDog/certstream-java/files/4444295/stacktrace.txt)

**Comment by joshbooks** [comment]
@nitram22 could you take a look at https://github.com/CaliDog/certstream-java/pull/8 when you have a minute and see if that works for you?

**Comment by nitram22** [comment]
Thanks for looking into it!
I'll test it tomorrow and get back to you
